version: '3.9'
services:
  db:
    image: postgres:13
    container_name: db
    hostname: db_host
    ports:
      - "5432:5432"
    env_file: 
      - .env
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - transcendence
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app


  frontend:
    build: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - transcendence
    expose:
      - 8080
    volumes:
      - ./frontend:/usr/src/app

networks:
  transcendence: